name: "Release Requirements"

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master
    paths:
      - 'go.mod'
      - 'go.sum'
      - '**/*.go'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  require-release-labels:
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #v4.1.6
      - name: Release Labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAGIC_COMMENT_HINT: "<!-- release-requirements:require-release-labels:comment -->"
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_REPOSITORY: ${{ github.repository }}
        run: |
          echo "Checking PR #$PR_NUMBER"

          labels=$(gh pr view "$PR_NUMBER" --json labels -q '.labels[].name')
  
          echo "Labels on PR:"
          echo "$labels"
          
          release_labels=$(echo "$labels" | grep -E '^Release: (major|minor|patch)' || true)
          
          if [[ -z "$release_labels" ]]; then
            num_release_labels=0
          else
            num_release_labels=$(echo "$release_labels" | grep -c .)
          fi


          echo "Number of valid release labels: $num_release_labels"

          if [[ "$num_release_labels" -eq 0 ]]; then
            echo "❌ No Release: label found. Please add one of: Release: major, Release: minor, or Release: patch."
            ./.github/scripts/pr_comments.sh --write-comment="$(cat ./.github/comment_templates/release_requirements--no-label.md)"
            exit 1
          elif [[ "$num_release_labels" -gt 1 ]]; then
            echo "❌ Multiple Release: labels found. Please ensure only one of: Release: major, minor, or patch."
            ./.github/scripts/pr_comments.sh --write-comment="$(cat ./.github/comment_templates/release_requirements--multiple-labels.md)"
            exit 1
          else
            echo "PR is valid, cleaning up comment"
            ./.github/scripts/pr_comments.sh --cleanup-comment
          fi

          echo "✅ Valid release label detected: $release_labels"